version: '3.8'

services:
  deepsynth-trainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepsynth-trainer-gpu
    ports:
      - "5001:5000"
    volumes:
      # Mount state directory for persistence
      - ./apps/web/state:/app/apps/web/state
      # Mount output directories
      - ./trained_model:/app/trained_model
      - ./datasets:/app/datasets
      - ./benchmarks:/app/benchmarks
      # Mount logs
      - ./logs:/app/logs
    environment:
      # HuggingFace Configuration
      - HF_TOKEN=${HF_TOKEN}
      - HF_USERNAME=${HF_USERNAME}

      # Flask Configuration
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key}
      - HOST=0.0.0.0
      - PORT=5000

      # CUDA Configuration for GPU training
      - CUDA_VISIBLE_DEVICES=0
      - TORCH_CUDA_ARCH_LIST=7.0;7.5;8.0;8.6;8.9;9.0

      # Python Configuration
      - PYTHONUNBUFFERED=1

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    restart: unless-stopped

    command: python3 -m apps.web --mode=training

networks:
  default:
    name: deepsynth-network
