version: '3.8'

services:
  deepsynth-ui:
    build: 
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: deepsynth-dataset-generator
    ports:
      - "5000:5000"
    # Ensure GPU is available in non-swarm Compose
    gpus: all
    volumes:
      # Mount state directory for persistence
      - ./web_ui/state:/app/web_ui/state
      # Mount output directories
      - ./generated_images:/app/generated_images
      - ./trained_model:/app/trained_model
      # Mount logs
      - ./logs:/app/logs
    environment:
      # HuggingFace Configuration
      - HF_TOKEN=${HF_TOKEN}
      - HF_USERNAME=${HF_USERNAME}

      # Flask Configuration
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key}
      - HOST=0.0.0.0
      - PORT=5000

      # CUDA Configuration (if using GPU)
      - CUDA_VISIBLE_DEVICES=0
      - TORCH_CUDA_ARCH_LIST=7.0;7.5;8.0;8.6;8.9;9.0

      # Python Configuration
      - PYTHONUNBUFFERED=1

      # State directory configuration
      - DEEPSYNTH_UI_STATE_DIR=/app/web_ui/state

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    restart: unless-stopped

    command: python3 -m apps.web

networks:
  default:
    name: deepsynth-network
